# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200)),
            ],
        ),
    ]
